let cart=[];function filterMenu(cat,btn){document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));btn.classList.add('active');const cards=document.querySelectorAll('.dish-card');cards.forEach(card=>{if(cat==='all'||card.getAttribute('data-cat')===cat){card.style.display='block'}else{card.style.display='none'}})}
function openAR(model,name){window.location.href=`ar-viewer.html?model=${model}&name=${encodeURIComponent(name)}`}
function addToCart(name,price){cart.push({name,price});updateCart();showToast(`${name} added to cart!`)}
function updateCart(){const badge=document.getElementById('cartBadge');const body=document.getElementById('cartBody');const ftr=document.getElementById('cartFtr');badge.textContent=cart.length;if(cart.length===0){body.innerHTML='<p class="empty-msg">Your cart is empty 😔</p>';ftr.style.display='none';return}
let html='';let subtotal=0;cart.forEach((item,idx)=>{subtotal+=item.price;html+=`<div style="display:flex;justify-content:space-between;align-items:center;padding:12px;background:var(--card);border-radius:12px;margin-bottom:12px"><div><strong>${item.name}</strong><br/><span style="color:var(--accent)">₹${item.price}</span></div><button onclick="removeFromCart(${idx})" style="background:rgba(255,0,0,0.2);color:#ff3333;border:none;padding:8px 12px;border-radius:8px;cursor:pointer">Remove</button></div>`});body.innerHTML=html;const gst=Math.round(subtotal*0.05);const total=subtotal+gst;document.getElementById('sub').textContent=`₹${subtotal}`;document.getElementById('gst').textContent=`₹${gst}`;document.getElementById('tot').textContent=`₹${total}`;ftr.style.display='block'}
function removeFromCart(idx){cart.splice(idx,1);updateCart();showToast('Item removed')}
function toggleCart(){document.getElementById('cartOverlay').classList.toggle('active');document.getElementById('cartDrawer').classList.toggle('active')}
function placeOrder(){if(cart.length===0)return;alert(`Order placed! Total: ₹${cart.reduce((sum,item)=>sum+item.price,0)+Math.round(cart.reduce((sum,item)=>sum+item.price,0)*0.05)}\n\nThank you for ordering!`);cart=[];updateCart();toggleCart()}
function showToast(msg){const toast=document.getElementById('toast');toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2000)}
